{
  "ppgnn": {
    "model": {
      "hidden": 64,
      "layers": 2,
      "dt": 0.1,
      "dropout": 0.7,
      "norm_type": "rw",
      "jacobi_steps": 2,
      "use_x_only": true,
      "y0_mode": "learned",
      "alpha0": 0.2,
      "beta0": 0.1,
      "dx0": 0.0001,
      "dy0": 0.8,
      "norm": "BatchNorm1d",
      "lift_type": "mlp",
      "lift_layers": 2
    },
    "train": {
      "epochs": 900,
      "lr": 0.002,
      "weight_decay": 0.0005,
      "clip_value":
    }
  },
  "gcn": {
    "model": {
      "hidden": 64,
      "layers": 2,
      "dropout": 0.4,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 200,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  },
  "sage": {
    "model": {
      "hidden": 64,
      "layers": 2,
      "dropout": 0.4,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 200,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  },
  "gat": {
    "model": {
      "hidden": 8,
      "heads": 8,
      "layers": 2,
      "dropout": 0.4,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 200,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  }
}