{
  "ppgnn": {
    "model": {
      "hidden": 64,
      "layers": 3,
      "dt": 0.1,
      "dropout": 0.5,
      "norm_type": "sym",
      "jacobi_steps": 2,
      "use_x_only": true,
      "y0_mode": "ones",
      "alpha0": 0.2,
      "beta0": 0.1,
      "dx0": 0.7,
      "dy0": 0.8,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 50,
      "lr": 0.001,
      "weight_decay": 0.0,
      "clip_value": 5.0
    }
  },
  "gcn": {
    "model": {
      "hidden": 128,
      "layers": 3,
      "dropout": 0.5,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 50,
      "lr": 0.01,
      "weight_decay": 0.0
    }
  },
  "sage": {
    "model": {
      "hidden": 128,
      "layers": 3,
      "dropout": 0.5,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 50,
      "lr": 0.01,
      "weight_decay": 0.0
    }
  },
  "gat": {
    "model": {
      "hidden": 8,
      "heads": 8,
      "layers": 3,
      "dropout": 0.5,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 50,
      "lr": 0.005,
      "weight_decay": 0.0
    }
  }
}
