{
  "ppgnn": {
    "model": {
      "hidden": 128,
      "layers": 15,
      "dt": 0.1,
      "dropout": 0.4,
      "norm_type": "sym",
      "jacobi_steps": 2,
      "use_x_only": false,
      "y0_mode": "learned",
      "alpha0": 0.2,
      "beta0": 0.1,
      "dx0": 0.7,
      "dy0": 0.8,
      "norm": "BatchNorm1d"
    },
    "train": {
      "epochs": 710,
      "lr": 0.002,
      "weight_decay": 0.0005,
      "clip_value": 5.0
    }
  },
  "gcn": {
    "model": {
      "hidden": 128,
      "layers": 2,
      "dropout": 0.4,
      "norm": "BatchNorm1d"
    },
    "train": {
      "epochs": 600,
      "lr": 0.01,
      "weight_decay": 0.0005
    }
  },
  "sage": {
    "model": {
      "hidden": 128,
      "layers": 2,
      "dropout": 0.4,
      "norm": "None"
    },
    "train": {
      "epochs": 600,
      "lr": 0.01,
      "weight_decay": 0.0005
    }
  },
  "gat": {
    "model": {
      "hidden": 128,
      "heads": 8,
      "layers": 2,
      "dropout": 0.4,
      "norm": "None"
    },
    "train": {
      "epochs": 600,
      "lr": 0.01,
      "weight_decay": 0.0005
    }
  }
}