{
  "ppgnn": {
    "model": {
      "hidden": 128,
      "layers": 8,
      "dt": 0.10,
      "dropout": 0.4,
      "norm_type": "sym",
      "jacobi_steps": 2,
      "use_x_only": true,
      "y0_mode": "learned",
      "alpha0": 0.2,
      "beta0": 0.1,
      "dx0": 0.7,
      "dy0": 0.8
    },
    "train": {
      "epochs": 350,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value": 5.0

    }
  },
  "gcn": {
    "model": {
      "hidden": 128,
      "layers": 2,
      "dropout": 0.4
    },
    "train": {
      "epochs": 350,
      "lr": 0.01,
      "weight_decay": 0.0005
    }
 },
  "sage": {
    "model": {
      "hidden": 128,
      "layers": 2,
      "dropout": 0.5
    },
    "train": {
      "epochs": 300,
      "lr": 0.01,
      "weight_decay": 0.0005
    }
  },
  "gat": {
    "model": {
      "hidden": 16,
      "heads": 8,
      "layers": 2,
      "dropout": 0.5
    },
    "train": {
      "epochs": 300,
      "lr": 0.01,
      "weight_decay": 0.0005
    }
  }
}

