{
  "ppgnn": {
    "model": {
      "hidden": 64,
      "layers": 2,
      "dt": 0.05,
      "dropout": 0.8,
      "norm_type": "rw",
      "jacobi_steps": 1,
      "use_x_only": false,
      "y0_mode": "learned",
      "alpha0": 0.2,
      "beta0": 0.1,
      "dx0": 0.05,
      "dy0": 0.3,
      "norm": "LayerNorm",
      "custom": 1,              # 新增/显式打开
      "custom_gnn": "sage",       # 或 gcn/gat/transformer/...
      "heads": 1,               # 注意力/Transformer 可调
      "use_gating": true,       # 打开高频门控
      "lift_type": "mlp",
      "lift_layers": 2
    },
    "train": {
      "epochs": 600,
      "lr": 0.002,
      "weight_decay": 0.0005,
      "clip_value":
    }
  },
  "gcn": {
    "model": {
      "hidden": 64,
      "layers": 2,
      "dropout": 0.4,
      "norm": "none"
    },
    "train": {
      "epochs": 300,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  },
  "sage": {
    "model": {
      "hidden": 64,
      "layers": 2,
      "dropout": 0.4,
      "norm": "none"
    },
    "train": {
      "epochs": 300,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  },
  "gat": {
    "model": {
      "hidden": 8,
      "heads": 8,
      "layers": 2,
      "dropout": 0.4,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 300,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  }
}