{
  "dataset": {
    "format": "PowerGrid-size",
    "name": "tr20_te100",
    "train_dataset": "dataset20",
    "test_dataset": "dataset100"
  },
  "ppgnn": {
    "model": {
      "hidden": 64,
      "layers": 10,
      "dt": 0.1,
      "dropout": 0.5,
      "norm_type": "sym",
      "jacobi_steps": 2,
      "use_x_only": true,
      "y0_mode": "learned",
      "alpha0": 0.2,
      "beta0": 0.1,
      "dx0": 0.7,
      "dy0": 0.8,
      "norm": "BatchNorm1d",
      "lift_type": "mlp",
      "lift_layers": 2
    },
    "train": {
      "epochs": 300,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  },
  "gcn": {
    "model": {
      "hidden": 64,
      "layers": 10,
      "dropout": 0.2,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 300,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  },
  "sage": {
    "model": {
      "hidden": 64,
      "layers": 2,
      "dropout": 0.4,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 300,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  },
  "gat": {
    "model": {
      "hidden": 8,
      "heads": 8,
      "layers": 2,
      "dropout": 0.4,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 300,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  }
}