{
  "ppgnn": {
    "model": {
      "hidden": 128,
      "layers": 2,
      "dt": 0.1,
      "dropout": 0.7,
      "norm_type": "sym",
      "jacobi_steps": 1,
      "use_x_only": false,
      "y0_mode": "learned",
      "alpha0": 0.2,
      "beta0": 0.1,
      "dx0": 0.0007,
      "dy0": 0.8,
      "norm": "none",
      "lift_type": "mlp",
      "lift_layers": 1
    },
    "train": {
      "epochs": 400,
      "lr": 0.05,
      "weight_decay": 0.0001,
      "clip_value":
    }
  },
  "gcn": {
    "model": {
      "hidden": 64,
      "layers": 2,
      "dropout": 0.2,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 200,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  },
  "sage": {
    "model": {
      "hidden": 64,
      "layers": 2,
      "dropout": 0.2,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 200,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  },
  "gat": {
    "model": {
      "hidden": 8,
      "heads": 8,
      "layers": 2,
      "dropout": 0.2,
      "norm": "layernorm"
    },
    "train": {
      "epochs": 200,
      "lr": 0.01,
      "weight_decay": 0.0005,
      "clip_value":
    }
  }
}