{
  "ppgnn": {
    "model": {
      "hidden": 128,
      "layers": 2,
      "dt": 0.1,
      "dropout": 0.2,
      "norm_type": "sym",
      "jacobi_steps": 2,
      "use_x_only": true,
      "y0_mode": "ones"
    },
    "train": {
      "epochs": 2000,
      "lr": 0.002,
      "weight_decay": 0.0005,
      "clip_value": 5.0
    }
  },
  "gcn": {
    "model": {
      "hidden": 64,
      "layers": 2
    },
    "train": {
      "epochs": 200,
      "lr": 0.01,
      "weight_decay": 0.0005
    }
  }
}
